version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      prefix: ci
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
